name: CharacterAlarm
options:
  deploymentTarget:
    iOS: 14.0
  postGenCommand: bundle exec pod install

packages:
  R.swift.Library:
    url: https://github.com/mac-cain13/R.swift.Library
    from: 5.2.2

schemes:
  Local:
    build:
      targets:
        CharalarmLocal: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - name: CharacterAlarmTests
          parallelizable: true
          randomExecutionOrder: true
  Staging:
    build:
      targets:
        CharalarmStaging: all
    run:
      config: Debug
  Production:
    build:
      targets:
        CharalarmProduction: all
    run:
      config: Debug

targets:
  CharalarmLocal:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: CharacterAlarm
        excludes:
          - CharacterAlarm/Resource
      - path: CharacterAlarm/Resource
        type: folder
      - path: Config/Local
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: CharacterAlarm/CharacterAlarmRelease.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.CharacterAlarm
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: CharacterAlarm/Info.plist
        MARKETING_VERSION: 2.0.11
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Local
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: CharacterAlarm/CharacterAlarmDebug.entitlements
          API_ENDPOINT: http://localhost:8080
          RESOURCE_ENDPOINT: https://stg-resource.charalarm.com
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_ALARM_LIST: ca-app-pub-3940256099942544/2934735716
          ADMOB_CONFIG: ca-app-pub-3940256099942544/2934735716
        Release:
          CODE_SIGN_ENTITLEMENTS: CharacterAlarm/CharacterAlarmRelease.entitlements
          API_ENDPOINT: http://localhost:8080
          RESOURCE_ENDPOINT: https://stg-resource.charalarm.com
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_ALARM_LIST: ca-app-pub-3940256099942544/2934735716
          ADMOB_CONFIG: ca-app-pub-3940256099942544/2934735716
    dependencies:
      - package: R.swift.Library
        product: Rswift
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
    preBuildScripts:
      - script: ./Scripts/BuildPhases/rswift.sh
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/CharacterAlarm/Generated/R.generated.swift
  CharalarmStaging:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: CharacterAlarm
        excludes:
          - CharacterAlarm/Resource
      - path: CharacterAlarm/Resource
        type: folder
      - path: Config/Staging
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: CharacterAlarm/CharacterAlarmRelease.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.charalarm.staging
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: CharacterAlarm/Info.plist
        MARKETING_VERSION: 2.0.11
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Staging
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: CharacterAlarm/CharacterAlarmDebug.entitlements
          API_ENDPOINT: https://api-stg.charalarm.com
          RESOURCE_ENDPOINT: https://stg-resource.charalarm.com
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_ALARM_LIST: ca-app-pub-3940256099942544/2934735716
          ADMOB_CONFIG: ca-app-pub-3940256099942544/2934735716
        Release:
          CODE_SIGN_ENTITLEMENTS: CharacterAlarm/CharacterAlarmRelease.entitlements
          API_ENDPOINT: https://api-stg.charalarm.com
          RESOURCE_ENDPOINT: https://stg-resource.charalarm.com
          GAD_APPLICATION_IDENTIFER: ca-app-pub-3940256099942544~1458002511
          ADMOB_ALARM_LIST: ca-app-pub-3940256099942544/2934735716
          ADMOB_CONFIG: ca-app-pub-3940256099942544/2934735716
    dependencies:
      - package: R.swift.Library
        product: Rswift
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
    preBuildScripts:
      - script: ./Scripts/BuildPhases/rswift.sh
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/CharacterAlarm/Generated/R.generated.swift
  CharalarmProduction:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: CharacterAlarm
        excludes:
          - CharacterAlarm/Resource
      - path: CharacterAlarm/Resource
        type: folder
      - path: Config/Production
    dependencies:
      - package: R.swift.Library
        product: Rswift
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
    preBuildScripts:
      - script: ./Scripts/BuildPhases/rswift.sh
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/CharacterAlarm/Generated/R.generated.swift
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: CharacterAlarm/CharacterAlarmRelease.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.CharacterAlarm
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: CharacterAlarm/Info.plist
        MARKETING_VERSION: 2.0.11
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Production
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: CharacterAlarm/CharacterAlarmDebug.entitlements
          API_ENDPOINT: https://api.charalarm.com
          RESOURCE_ENDPOINT: https://resource.charalarm.com
          GAD_APPLICATION_IDENTIFER: ca-app-pub-5587141252700968~9053558907
          ADMOB_ALARM_LIST: ca-app-pub-5587141252700968/8220227024
          ADMOB_CONFIG: ca-app-pub-5587141252700968/1355204268
        Release:
          CODE_SIGN_ENTITLEMENTS: CharacterAlarm/CharacterAlarmRelease.entitlements
          API_ENDPOINT: https://api.charalarm.com
          RESOURCE_ENDPOINT: https://resource.charalarm.com
          GAD_APPLICATION_IDENTIFER: ca-app-pub-5587141252700968~9053558907
          ADMOB_ALARM_LIST: ca-app-pub-5587141252700968/8220227024
          ADMOB_CONFIG: ca-app-pub-5587141252700968/1355204268
  CharacterAlarmTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - CharacterAlarmTests
    settings:
      base:
        INFOPLIST_FILE: CharacterAlarmTests/Info.plist
    dependencies:
      - target: CharalarmLocal
  CharacterAlarmUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - CharacterAlarmUITests
    settings:
      base:
        INFOPLIST_FILE: CharacterAlarmUITests/Info.plist
    dependencies:
      - target: CharalarmLocal
