import Foundation

let CHARA_DOMAIN = "CHARA_DOMAIN"
let CHARA_NAME = "CHARA_NAME"

let ANONYMOUS_USER_NAME = "ANONYMOUS_USER_ID"
let ANONYMOUS_USER_PASSWORD = "ANONYMOUS_USER_PASSWORD"


// Default
let DEFAULT_CHARA_DOMAIN = "com.charalarm.yui"
let DEFAULT_CHARA_NAME = "井上結衣"
