import Foundation

let CHARA_DOMAIN = "CHARA_DOMAIN"
let CHARA_NAME = "CHARA_NAME"

let ANONYMOUS_USER_NAME = "ANONYMOUS_USER_NAME"
let ANONYMOUS_AUTH_TOKEN = "ANONYMOUS_AUTH_TOKEN"


// Default
let DEFAULT_CHARA_DOMAIN = "com.charalarm.yui"
let DEFAULT_CHARA_NAME = "井上結衣"
